// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAizAZCaWcALu7F2y-wz31w3uGcquOGkjo',
    appId: '1:586878001660:web:3f46ad80d138555c0cd279',
    messagingSenderId: '586878001660',
    projectId: 'ga-for-windows-2-3180',
    authDomain: 'ga-for-windows-2-3180.firebaseapp.com',
    storageBucket: 'ga-for-windows-2-3180.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJfOnz_h7Z9o5pt2vAb1k7L1Y21MTvdgI',
    appId: '1:586878001660:android:358498a2359f2c460cd279',
    messagingSenderId: '586878001660',
    projectId: 'ga-for-windows-2-3180',
    storageBucket: 'ga-for-windows-2-3180.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlSjkPlqxNctnvAAzSRtL_7NEo3IJ-4xw',
    appId: '1:586878001660:ios:ff94c699dbb6648d0cd279',
    messagingSenderId: '586878001660',
    projectId: 'ga-for-windows-2-3180',
    storageBucket: 'ga-for-windows-2-3180.firebasestorage.app',
    iosBundleId: 'com.example.stallseeker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlSjkPlqxNctnvAAzSRtL_7NEo3IJ-4xw',
    appId: '1:586878001660:ios:ff94c699dbb6648d0cd279',
    messagingSenderId: '586878001660',
    projectId: 'ga-for-windows-2-3180',
    storageBucket: 'ga-for-windows-2-3180.firebasestorage.app',
    iosBundleId: 'com.example.stallseeker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAizAZCaWcALu7F2y-wz31w3uGcquOGkjo',
    appId: '1:586878001660:web:a97f114cae3634120cd279',
    messagingSenderId: '586878001660',
    projectId: 'ga-for-windows-2-3180',
    authDomain: 'ga-for-windows-2-3180.firebaseapp.com',
    storageBucket: 'ga-for-windows-2-3180.firebasestorage.app',
  );
}
